### ISSUE TITLE
How to Train using Our Own Documents ?

### ISSUE THREAD

**Issue by Utomo88** [openai-php/laravel#13]
How to Train using Our Own Documents ?

when this features will be added ?
Thank you

**Comment by m7vm7v** [comment]
I also would love to see that, as far as I believe that is actually a chatgpt 4 feature, isn't it?

**Comment by pb30** [comment]
ChatGPT is separate from the OpenAI API, which this library covers. You can [fine-tune](https://platform.openai.com/docs/guides/fine-tuning) a model using this library, but requires your data in a very specific structured format. Otherwise you need to use a whole suite of different scripts/software to query on your own documents (see projects like LangChain). It's not something that OpenAI provides a direct solution for.
